/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica12;

import javax.swing.ImageIcon;

/**
 *
 * @author Antonio Jiménez Rodríguez
 */
public class IconPanel extends javax.swing.JPanel {

    /**
     * Creates new form ColorPanel
     * @param imageIcon
     */
    public IconPanel(ImageIcon imageIcon) {
        initComponents();
        buttonIcon.setIcon(imageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonIcon = new javax.swing.JButton();

        buttonIcon.setMaximumSize(new java.awt.Dimension(25, 25));
        buttonIcon.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param imageIcon 
     */
    public void setIcon(ImageIcon imageIcon){
        buttonIcon.setIcon(imageIcon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonIcon;
    // End of variables declaration//GEN-END:variables
}
