/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica12;

import sm.ajr.iu.Canvas2D;

/**
 *
 * @author Antonio Jiménez Rodríguez
 */
public class InternalFrame extends javax.swing.JInternalFrame {

    /******************************* PROPERTIES ******************************/
    
    /******************************* CONSTRUCTS ******************************/
    
    /**
     * Creates new form InternalFrame
     */
    public InternalFrame() {
        initComponents();
    }
    
    /*************************** GETTER AND SETTER ***************************/
    
    /**
     * Gets the canvas of the internal frame.
     * 
     * @return Canvas2D
     */
    public Canvas2D getCanvas2D(){
        return this.canvas;
    }

    /***************************** PUBLIC METHODS ****************************/
    
    /***************************** PRIVARE METHODS ***************************/
    
    /************************** JAVA GENERATED CODE **************************/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        canvas = new sm.ajr.iu.Canvas2D();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nuevo lienzo");
        setPreferredSize(new java.awt.Dimension(600, 400));

        canvas.setPreferredSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(canvas);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sm.ajr.iu.Canvas2D canvas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
