/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica14;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;

/**
 *
 * @author Antonio Jiménez Rodríguez
 */
public class WebcamInternalFrame extends javax.swing.JInternalFrame {

    /******************************* PROPERTIES ******************************/
    
    private Webcam webcam = null;
    
    /******************************* CONSTRUCTS ******************************/
    
    /**
     * Creates new form WebCamInternalFrame
     */
    private WebcamInternalFrame() 
    {
        initComponents();
        webcam = Webcam.getDefault();
        if (webcam != null) {
            WebcamPanel visualArea = new WebcamPanel(webcam);
            if (visualArea != null) {
                getContentPane().add(visualArea, BorderLayout.CENTER);
                pack();
            }
        }
        
    }

    /*************************** GETTER AND SETTER ***************************/

    /***************************** PUBLIC METHODS ****************************/
    
    /**
     * Metodo que obtiene una instancia de la clase WebcamInternalFrame.
     * 
     * @return WebcamInternalFrame instancia de la clase WebcamInternalFrame.
     */
    public static WebcamInternalFrame getInstance()
    {
        WebcamInternalFrame webcamInternalFrame = new WebcamInternalFrame();
        return (webcamInternalFrame.webcam != null ? webcamInternalFrame : null);
    }
    
    /**
     * Método que obtiene una instantanea del frame actual de la webcam.
     * 
     * @return BufferedImage instantanea del frame actual de la webcam.
     */
    public BufferedImage getImage()
    {
        return webcam != null ? webcam.getImage() : null;
    }
    /***************************** PRIVARE METHODS ***************************/
    
    /************************** JAVA GENERATED CODE **************************/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
